In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Numpy
    Numeric Python의 약자
    통계 연산시 사용
    과학 계산 컴퓨팅, 데이터 분석에 필요한 기본적인 패키지
    
    Numpy 배열은 리스트와 거의 흡사
    리스트보다 훨씬 빠르고 메모리 효율성이 높다.

#### Numpy 배열 만드는 방법
    1) array()
    2) random 모듈의 함수 사용

In [2]:
import numpy as np

In [3]:
myList = [4, 5, 6, 7]
myList
type(myList)

'*' * 40

myArr = np.array(myList)
myArr # 출력 결과 [ ] 안에 값이 나열되지만 comma로 구분되지는 않는다(print하면)
type(myArr) # ndarray 클래스는 다차원행렬구조를 지원하는 Numpy의 핵심 클래스

[4, 5, 6, 7]

list

'****************************************'

array([4, 5, 6, 7])

numpy.ndarray

In [4]:
# 슬라이싱에서 리스트와 넘파이 배열의 차이

# list-deep copy
myList_sub = myList[1:3]
myList_sub

myList_sub[0] = -5
myList

'*' * 40

# np array-shallow copy
myArr_sub = myArr[1:3]
myArr_sub

myArr_sub[0] = -5
myArr

[5, 6]

[4, 5, 6, 7]

'****************************************'

array([5, 6])

array([ 4, -5,  6,  7])

In [5]:
# rand() 함수 사용

a = np.random.rand(5)
a
type(a)

b = np.random.randint(1, 10)
b
type(b)

c = np.random.randn(10) # 가우시안 표준분포
c
type(c)

array([0.83259377, 0.14574401, 0.3868098 , 0.20234381, 0.84830672])

numpy.ndarray

9

int

array([-0.76007459,  2.10118435, -1.02651768, -1.47240989,  0.76286695,
        1.26795945, -0.80848642, -1.22104164,  0.2186491 ,  1.09680125])

numpy.ndarray

#### np 배열의 초기화
    arange()
    zeros()
    full()
    ones()
    eye()
    ...

In [6]:
np.zeros(10)
np.ones(10)
np.zeros(10) + 7
np.full(10, 7.)

'*' * 40

np.zeros((3, 5))
np.ones((3, 5))
np.zeros((3, 5)) + 7
np.full((3, 5), 7.)

'*' * 40

np.eye(1)
np.eye(2)
np.eye(3)

'*' * 40

np.arange(3)
np.arange(3, 7)
np.arange(3, 10, 2)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

'****************************************'

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

'****************************************'

array([[1.]])

array([[1., 0.],
       [0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

'****************************************'

array([0, 1, 2])

array([3, 4, 5, 6])

array([3, 5, 7, 9])

### np 배열과 리스트의 차이점
    1. np 배열은 원본을 바로 바꿈으로써 메모리 효율성이 뛰어나다.
    2. 리스트는 여러가지 자료형이 원소로 올 수 있지만
       np 배열은 한 가지 자료형만 원소로 쓰일 수 있다...또 메모리 효율성

In [7]:
L = [1, 2, 3, '4']
L
np.array(L)
np.array([1, 2, 3, 4.])
np.array([1, 2, 3, 4.], dtype='int')
np.array([1, 2, 3, 4.], dtype=np.int32)

[1, 2, 3, '4']

array(['1', '2', '3', '4'], dtype='<U11')

array([1., 2., 3., 4.])

array([1, 2, 3, 4])

array([1, 2, 3, 4])

### np 배열에서 사용되는 속성, 함수
    ndim shape size type dtype
    astype() reshape()

In [8]:
arr1 = np.array([[1.0, 2, 3], [4, 5, 6]], dtype=np.int32)
arr1
type(arr1)

'*' * 50

# np.dtype(arr1) # 이건 안 됨
np.ndim(arr1)
np.shape(arr1)
np.size(arr1)

'*' * 50

arr1.dtype
arr1.ndim
arr1.shape
arr1.size

'*' * 50

arr1_1 = arr1.astype(np.float32)
arr1.dtype # arr1을 바꾸는 게 아니라 리턴한다
arr1_1.dtype

array([[1, 2, 3],
       [4, 5, 6]])

numpy.ndarray

'**************************************************'

2

(2, 3)

6

'**************************************************'

dtype('int32')

2

(2, 3)

6

'**************************************************'

dtype('int32')

dtype('float32')

In [9]:
arr2 = np.arange(0, 32)
arr2.reshape(4, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])