In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### 랜덤 함수와 seed 값 설정
    시드 값은 한 번만 설정해주면 계속 적용된다.
    시드는 보통 현재 시각 등을 이용해서 자동으로 정해지지만
    우리가 수동으로도 설정할 수 있다.
    특정한 시드 값이 사용되면 그 다음에 만들어지는 난수들을 예측할 수 있다.

In [2]:
import numpy as np

In [3]:
np.random.seed(0)

arr1 = np.random.randn(4, 4)
arr1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [4]:
arr2 = np.arange(1, 10)
arr2

arr3 = arr2.reshape(3, 3)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 인덱싱, 슬라이싱

In [5]:
narray = np.arange(5)
narray

array([0, 1, 2, 3, 4])

In [6]:
narray[1], narray[-1]
narray[1:]
narray[:]
narray[2:4]

(1, 4)

array([1, 2, 3, 4])

array([0, 1, 2, 3, 4])

array([2, 3])

In [7]:
narray2 = np.random.randint(10, 20, 16).reshape(4, 4)
narray2

array([[12, 13, 18, 11],
       [13, 13, 13, 17],
       [10, 11, 19, 19],
       [10, 14, 17, 13]])

In [8]:
narray2[0][2]
narray2[0, 2]

'*' * 50

narray2[1]
narray2[1, ]
narray2[1, :]
narray2[1:2, :] # 차원이 다르다

'*' * 50

narray2[:, 3]
narray2[:, 3:]

'*' * 50

narray2[:, 1:3]

18

18

'**************************************************'

array([13, 13, 13, 17])

array([13, 13, 13, 17])

array([13, 13, 13, 17])

array([[13, 13, 13, 17]])

'**************************************************'

array([11, 17, 19, 13])

array([[11],
       [17],
       [19],
       [13]])

'**************************************************'

array([[13, 18],
       [13, 13],
       [11, 19],
       [14, 17]])

#### 인덱싱과 조건 슬라이싱

In [9]:
arr1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [10]:
arr1 > 0
arr1[arr1 > 0]
arr1[arr1 < 0]

'*' * 50

arr1[arr1 < 0] = 0
arr1

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

array([1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799,
       0.95008842, 0.4105985 , 0.14404357, 1.45427351, 0.76103773,
       0.12167502, 0.44386323, 0.33367433])

array([-0.97727788, -0.15135721, -0.10321885])

'**************************************************'

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [11]:
# where 함수
arr1_1 = np.where(arr1 > 0, arr1, -1) # 삼항 연산자와 비슷
arr1_1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -1.        ,  0.95008842, -1.        ],
       [-1.        ,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [12]:
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
arr2

bool_idx = arr2 > 2
bool_idx
arr2[bool_idx]

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[False, False],
       [ True,  True],
       [ True,  True]])

array([3, 4, 5, 6])

#### 통계 함수
    sum, mean, min, max, argmin, argmax, cumsum(누적합)

In [13]:
narray2

array([[12, 13, 18, 11],
       [13, 13, 13, 17],
       [10, 11, 19, 19],
       [10, 14, 17, 13]])

In [14]:
np.sum(narray2)
narray2.sum()

np.sum(narray2, axis=1) # axis=1 : 열...행마다의 합이 열로 나온다
narray2.sum(axis=1)

np.sum(narray2, axis=0)
narray2.sum(axis=0)

223

223

array([54, 56, 59, 54])

array([54, 56, 59, 54])

array([45, 51, 67, 60])

array([45, 51, 67, 60])